### ISSUE TITLE
Improve Falco definition

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1003]
/area documentation

**What would you like to be added**:
Be clear on what Falco does and does not do. And how it integrates with ecosystem tools.

**Why is this needed**:
Definition should be consistent across website and repositories.

```[tasklist]
### Tasks
- [x] Finalize the definition for Falco.
- [x] Go through each repository in Falco organization and ensure consistency
- [x] Update Falco.org landing page.
- [x] Update Falco.org About page.
- [ ] Update Falco.org Docs pages.
```

**Comment by leogr** [comment]
See https://github.com/falcosecurity/falco-website/pull/1069

**Comment by leogr** [comment]
@LucaGuerra and I went through each repository, and now they seem to be consistent. See #1005

**Comment by leogr** [comment]
About page :point_down: 
https://github.com/falcosecurity/falco-website/pull/1095
