### ISSUE TITLE
Create a glossary for Falco terms

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1006]
/area documentation

**What would you like to be added**:
- Improve understanding of Falco content - should be understandable by someone that doesn’t know C++, anything about the kernel
- Provide references for individuals to learn more about eBFP, kernel security, syscalls, and more.

**Why is this needed**:
users need a good context about Falco terms.

```[tasklist]
### Tasks
- [ ] Define and add references for syscalls
- [ ] Define and add references for Kernel
- [ ] Kernel space and user space
- [ ] Define and add references for alerts
- [ ] Define and add references for gRPC
- [ ] Define and add references for Runtime Security
- [ ] Define and add references for plugins
- [ ] Define and add references for extractors
- [ ] Define and add references for sources
- [ ] Define and add references for drivers
- [ ] Define and add references for eBPF
- [ ] Define and add references for probe
- [ ] Define and add references for module
- [ ] Define and add references for rule
- [ ] Define and add references for rules file
- [ ] Define and add references for macro
- [ ] Define and add references for condition
- [ ] Define and add references for  list
- [ ] Define and add references for output
- [ ] Define and add references for rule fields
- [ ] Define and add references for ring buffer
- [ ] Define and add references for exporter
- [ ] Define and add references for event generator
- [ ] Define and add references for priority
- [ ] Define and add references for tags
- [ ] Define and add references for exceptions
```
