### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [falcosecurity/falco-website#972]
This issue is being opened in the context of the following request: https://cncfservicedesk.atlassian.net/browse/CNCFSD-1770

### Existing website info

- UA site tag: [`UA-40398182-19`][ua]
  - Insert link to **Google UA console here**.
  - TBD if there are other UA site tags being used (e.g., a separate tag for blog entries)
- Netlify hosted (does CNCF have access?)

---

This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks

There are quite a few ways that we migrate to GA4. The following is, in most cases, the simplest:

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **[`G-D5DEHT7DJ1`][ga4]**
- [x] [Connect][] the UA ID from the GA4 site tag
- [x] Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection], "Google Analytics 4 - in production only", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-D5DEHT7DJ1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-D5DEHT7DJ1');
  </script>
  {% endif %}
  ```
- [x] Confirm that the GA4 site tag is receiving events
- [x] #973
- [x] Link GA4 ID to search console

If it is still relevant for the UA site tag to receive events, then:

- [x] Link the UA and GA4 site tags (in either direction, which ever is most convenient)
- [x] Confirm that the UA site tag is still receiving events

### Google GA4 property created in 2022

Aiz granted me access to the [UA console][ua] -- thanks! That allowed me to see that it was **already connected to a GA4** property (with a data stream ID of `G-EN7HNEVL6X`), which was created by **Joseph Lee on Dec. 6, 2022** -- as you can see from the change history of [GA4 ID's console][ga4-sysdig].

It seems that Joseph made further changes to that property yesterday, according to the change log. How would you like to proceed? We now have two GA4 site tags: one in each of the Sysdig and CNCF orgs. We probably don’t want to keep both. 

@aijamalnk commented that we would be using the CNCF GA4 ID.

### Followup items and related items

- #984

/cc @caniszczyk @nate-double-u

---

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/
[ga4]: https://analytics.google.com/analytics/web/#/a163836834p377784592/admin/streams/table/5249833510
[ua]: https://analytics.google.com/analytics/web/#/a40398182w185781754p182920300
[ga4-sysdig]: https://analytics.google.com/analytics/web/#/a40398182p345412682

**Comment by chalin** [comment]
@leogr @LucaGuerra - can either of you confirm whether there are any other UA IDs used by the website that would need to be migrated? (I don't think so, but prefer asking.)

**Comment by chalin** [comment]
@LucaGuerra et al.: also, you'll need to ensure that the old UA ID wasn't auto-linked to an (auto-)created GA4 ID by Google. If you grant me access to the UA ID console, I can do the necessary checks. Otherwise, you'll need to look under the property config of Admin section.

**Comment by LucaGuerra** [comment]
I believe @aijamalnk can confirm here but I don't think there should be any more UA IDs.

**Comment by aijamalnk** [comment]
Thank you @chalin! Granted you the necessary access.

**Comment by chalin** [comment]
Search console linked to CNCF GA4 property:

> <img width="600" alt="image" src="https://github.com/falcosecurity/falco-website/assets/4140793/c17d18d6-9e9f-4220-b944-54e43c3db0e1">
